/** Declaration file generated by dts-gen */

export = codemap;

declare function codemap(rootMap: any): any;

declare namespace codemap {
    const globalId: number;

    const prototype: {
    };

    function alter(p0: any): any;

    function container(p0: any): any;

    function named(name: any, fn: any, ...args: any[]): any;

    namespace named {
        const prototype: {
        };

    }

}

